config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "caseworkers#sign_in"
  resources :boards
  resources :clients do
    collection do
      get :recent
    end
  end
  resources :caseworkers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :caseworker


  def self.count_new(last_seen)
    all.select { |c| c.recent?(last_seen) }.count
  end

  def is_completed?
    completed_at
  end

  def is_completed
    if is_completed? then true
    else return false
    end
  end

  def is_completed=(bool)
    if bool == false || bool == nil || bool == "false"
      self.completed_at = nil
    else  self.completed_at = DateTime.now
    end
  end

  def complete!
    self.completed_at = DateTime.now
    self.save
  end

  def recent?(last_seen)
    created_at > last_seen
  end

  def fmt_date
    date.in_time_zone("America/Chicago").strftime("%d %b %Y") if date
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    if user_signed_in? && current_user.is_admin? then
      @clients = Client.all
    elsif user_signed_in? && current_user.is_caseworker? then
      @clients = current_user.caseworker.clients
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  # GET /clients
  # GET /clients.json
  def recent
    if current_user.is_admin?
      @clients = Client.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])
    authorize! :read, @client

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new
    authorize! :create, @client

    @client.date = DateTime.now
    if user_signed_in?
      @client.caseworker = current_user.caseworker
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
    authorize! :update, @client
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    authorize! :create, @client

    respond_to do |format|
      if not @client.caseworker.can_add_clients?
        @client.errors[:base] << "You are past your limit.  Please come back later."
        format.html { render :action => "new" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      elsif @client.save
        format.html { redirect_to @client, :notice => 'Client was successfully created.' }
        format.json { render :json => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])
    authorize! :update, @client

    respond_to do |format|
      if @client.update_attributes(client_params)
        format.html { redirect_to @client, :notice => 'Client was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    authorize! :update, @client
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :ok }
    end
  end

  private

  def client_params
    params.require(:client).permit(
       :date,
       :caseworker_id,
       :name,
       :sex,
       :weight,
       :age,
       :height,
       :biketype,
       :helmet,
       :lock,
       :reason,
       :ridden_before
    )
  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :date %>
<% if user_signed_in? -%>
  <%= f.hidden_field :caseworker_id %>
<% end -%>

  <table>
<% if current_user.is_admin? -%>
    <tr>
      <td><%= f.label :is_completed, "Status" %><br /></td>
      <td class="field">
	<%= f.select :is_completed, [["pending", false], ["ready for pickup", true]] %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :caseworker_id, "Caseworker" %><br /></td>
      <td class="field"><%= f.collection_select :caseworker_id, Caseworker.all, :id, :name %></td>
    </tr>
<% end -%>
    <tr>
      <td><%= f.label :name, "Client name" %><br /></td>
      <td class="field"><%= f.text_field :name %></td>
    </tr><tr>
      <td><%= f.label :sex, "Gender" %><br /></td>
      <td class="field">
	<%= f.select :sex, ["male", "female", "other"] %>
      </td>
    </tr><tr>
      <td><%= f.label :weight %><br /></td>
      <td class="field"><%= f.text_field :weight, :size => 5 %></td>
    </tr><tr>
      <td><%= f.label :age %><br /></td>
      <td class="field"><%= f.text_field :age, :size => 5 %></td>
    </tr><tr>
      <td><%= f.label :height %><br /></td>
      <td class="field"><%= f.text_field :height, :size => 5 %></td>
    </tr><tr>
      <td><%= f.label :biketype %><br /></td>
      <td class="field">
	<%= f.select :biketype, ["Any", "Mountain", "Road", "Cruiser"] %>
      </td>
    </tr><tr>
      <td colspan=2>
	Road Bikes have drop handlebars and skinny tires.<br />
	Mountain bikes have straight handlebars and thick knobby tires.<br />
	Cruiser bikes are made for upright city riding.
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <td>
	<%= f.label :helmet, "Does the client need a helmet?" %>
      </td>
      <td>
	<%= f.select :helmet, [["yes", true], ["no", false]] %>
      </td>
    </tr><tr>
      <td>
	<%= f.label :lock, "Does the client need a lock?" %>
      </td>
      <td>
	<%= f.select :lock, [["yes", true], ["no", false]] %>
      </td>
    </tr><tr>
      <td colspan=2>
	<%= f.label :reason, "Why does the client need a bike?"%><br />
      </td>
    </tr><tr>
      <td colspan=2>
	<%= f.text_area :reason, :rows => 5 %>
      </td>
    </tr><tr>
      <td>
	<%= f.label :ridden_before, "Have they ridden a bike before?" %>
      </td>
      <td class="field">
	<%= f.select :ridden_before, [["yes", true], ["no", false]] %>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Clients</h1>
<% if current_user.is_caseworker? -%>
<p>
  <b>You can apply for a maximum of <%= current_user.caseworker.limit %> clients at a time.</b>
</p>
<% end -%>
<div id="data">

<table>
  <tr>
    <th>Name</th>
    <th>Application Filled</th>
<% if current_user.is_admin? -%>
    <th>Sex</th>
    <th>Weight</th>
    <th>Age</th>
    <th>Height</th>
    <th>Biketype</th>
    <th>Helmet</th>
    <th>Lock</th>
    <th>Caseworker</th>
<% end -%>
    <th>Status</th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%=link_to_client client %></td>
    <td><%=h client.fmt_date %></td>
<% if current_user.is_admin? -%>
    <td><%=h client.sex %></td>
    <td><%=h client.weight %></td>
    <td><%=h client.age %></td>
    <td><%=h client.height %></td>
    <td><%=h client.biketype %></td>
    <td><%=h client.helmet ? "needs helmet" : "not required" %></td>
    <td><%=h client.lock ? "needs lock" : "not required" %></td>
    <td><%=link_to_caseworker client.caseworker %></td>
<% end -%>
    <td><font color="<%= client.is_completed? ? 'green' : 'red' %>"><%= client.is_completed? ? "complete!" : "pending" %></font></td>
    <td>
      <%= link_to 'Show', client %>
      <%= link_to 'Edit', edit_client_path(client) %>
      <%= link_to 'Delete', client, :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
</div>

<br />

<% if current_user.is_caseworker? && current_user.caseworker.can_add_clients? -%>
<%= link_to 'New client', new_client_path %>
<%# elsif current_user.is_admin? -%>
<%# link_to 'New client', new_client_path %>
<% end -%>
<%= link_to 'Home', root_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Back', clients_path %>

app/views/clients/recent.html.erb
<h1>New Applications</h1>

<div> Your last login was at <%= current_user.last_sign_in_at %></div>
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th>Caseworker</th>
    <th>Created at</th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><div style='color: red'><%= client.recent?(current_user.last_sign_in_at) ? "new" : "" %></div></td>
    <td><%=link_to_client client %></td>
    <td><%=link_to_caseworker client.caseworker %></td>
    <td><%=h client.created_at %></td>

    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Delete', client, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% unless current_user.is_admin? -%>
<%= link_to 'New client', new_client_path %>
<% end -%>
<%= link_to 'Home', root_path %>

app/views/clients/show.html.erb
<h1>Client Application</h1>
<div id="data">
  <table>
<% if current_user.is_admin? -%>
    <tr>
      <td class="label"><b>Ready for pickup:</b></td>
      <td><font color='<%= @client.is_completed? ? 'green' : 'red' %>'><%=h @client.is_completed %></font></td>
    </tr>
<% elsif current_user.is_caseworker? && @client.is_completed?-%>
    <tr>
      <td colspan=2 align=center><font color="green"><b>Ready for pickup!</b></font></td>
    </tr>
<% end -%>
    <tr>
      <td class="label"><b>Name:</b></td>
      <td><%=h @client.name %></td>
    </tr><tr>
      <td class="label"><b>Date:</b></td>
      <td><%=h @client.fmt_date %></td>
    </tr><tr>
      <td class="label"><b>Sex:</b></td>
      <td><%=h @client.sex %></td>
    </tr><tr>
      <td class="label"><b>Weight:</b></td>
      <td><%=h @client.weight %></td>
    </tr><tr>
      <td class="label"><b>Age:</b></td>
      <td><%=h @client.age %></td>
    </tr><tr>
      <td class="label"><b>Height:</b></td>
      <td><%=h @client.height %></td>
    </tr><tr>
      <td class="label"><b>Biketype:</b></td>
      <td><%=h @client.biketype %></td>
    </tr><tr>
      <td class="label"><b>Helmet:</b></td>
      <td><%=h @client.helmet ? "needed" : "not needed" %></td>
    </tr><tr>
      <td class="label"><b>Lock:</b></td>
      <td><%=h @client.lock ? "needed" : "not needed" %></td>
    </tr><tr>
      <td class="label"><b>Reason:</b></td>
      <td><%=h @client.reason %></td>
    </tr><tr>
      <td class="label"><b>Ridden before:</b></td>
      <td><%=h @client.ridden_before %></td>
    </tr>
<% if current_user.is_admin? -%>
    <tr>
      <td class="label"><b>Caseworker:</b></td>
      <td><%=link_to @client.caseworker.name, @client.caseworker %></td>
    </tr>
<% end -%>
  </table>

</div>

<%= link_to 'Edit', edit_client_path(@client) %> |
<% if current_user.is_caseworker? %>
<%= link_to 'Back', clients_path %>
<% elsif current_user.is_admin? -%>
<%= link_to 'Back', recent_clients_path %>
<% end -%>