config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "caseworkers#sign_in"
  resources :boards
  resources :clients do
    collection do
      get :recent
    end
  end
  resources :caseworkers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :authenticate_user!

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
    authorize! :read, Board

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])
    authorize! :read, @board

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new
    @board.user_id = current_user.id
    authorize! :create, @board

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
    authorize! :update, @board
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])
    authorize! :create, @board

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, :notice => 'Board was successfully created.' }
        format.json { render :json => @board, :status => :created, :location => @board }
      else
        format.html { render :action => "new" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])
    authorize! :update, @board

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, :notice => 'Board was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @board.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    authorize! :update, @board
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :ok }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= form_for(@board) do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id %>
  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Post" %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing board</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<h1>Listing boards</h1>

<table>
  <tr>
    <th>Admin</th>
    <th>Posted at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% @boards.each do |board| %>
  <tr>
    <td><%= board.user.email if board.user %></td>
    <td><%= board.fmt_date %></td>
  </tr><tr>
    <td colspan=2>
      <div class="board-text">
	<%= board.text %>
      </div>
    </td>
  </tr>
<% if can? :update, board -%>
  <tr>
    <td><span><%= link_to 'Show', board %></span>
    <span><%= link_to 'Edit', edit_board_path(board) %></span>
    <span><%= link_to 'Delete', board, :confirm => 'Are you sure?', :method => :delete %></span></td>
  </tr>
<% end -%>
  <tr>
    <td colspan=2>&nbsp;<td>
  </tr>
<% end %>
</table>

<br />

<div><%= link_to 'New Post', new_board_path %></div>
<div><%= link_to 'Home', sign_in_caseworkers_path %></div>

app/views/boards/new.html.erb
<h1>New post</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p>
  <b>Admin:</b>
  <%= @board.user.email if @board.user %>
</p>

<div class="board-text">
  <%= @board.text %>
</div>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>