config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "caseworkers#sign_in"
  resources :boards
  resources :clients do
    collection do
      get :recent
    end
  end
  resources :caseworkers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/caseworker.rb
class Caseworker < ApplicationRecord
  belongs_to :user
  has_many :clients

	def can_add_clients?
	  if Client.where(caseworker_id: self.id).select {|c| not c.is_completed? }.count >= limit then false
	  else true
	  end
	end
end

app/controllers/caseworkers_controller.rb
class CaseworkersController < ApplicationController
  # GET /caseworkers
  # GET /caseworkers.json
  def sign_in
    @caseworkers = Caseworker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @caseworkers }
    end
  end

  # GET /caseworkers
  # GET /caseworkers.json
  def index
    @caseworkers = Caseworker.all
    authorize! :read, Caseworker

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @caseworkers }
    end
  end

  # GET /caseworkers/1
  # GET /caseworkers/1.json
  def show
    @caseworker = Caseworker.find(params[:id])
    authorize! :read, @caseworker

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @caseworker }
    end
  end

  # GET /caseworkers/new
  # GET /caseworkers/new.json
  def new
    @caseworker = Caseworker.new
    authorize! :create, @caseworker

    if user_signed_in?
      @caseworker.email = current_user.email
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @caseworker }
    end
  end

  # GET /caseworkers/1/edit
  def edit
    @caseworker = Caseworker.find(params[:id])
    authorize! :update, @caseworker
  end

  # POST /caseworkers
  # POST /caseworkers.json
  def create
    @caseworker = Caseworker.new(params[:caseworker])
    authorize! :create, @caseworker
    if user_signed_in?
      @caseworker.user_id = current_user.id
    end

    respond_to do |format|
      if @caseworker.save
        format.html { redirect_to @caseworker, :notice => 'Caseworker was successfully created.' }
        format.json { render :json => @caseworker, :status => :created, :location => @caseworker }
      else
        format.html { render :action => "new" }
        format.json { render :json => @caseworker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /caseworkers/1
  # PUT /caseworkers/1.json
  def update
    @caseworker = Caseworker.find(params[:id])
    authorize! :update, @caseworker

    respond_to do |format|
      if @caseworker.update_attributes(caseworker_params)
        format.html { redirect_to @caseworker, :notice => 'Caseworker was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @caseworker.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /caseworkers/1
  # DELETE /caseworkers/1.json
  def destroy
    @caseworker = Caseworker.find(params[:id])
    authorize! :update, @caseworker
    @caseworker.destroy

    respond_to do |format|
      format.html { redirect_to caseworkers_url }
      format.json { head :ok }
    end
  end

  private

  def caseworker_params
    params.require(:caseworker).permit(:name, :organization, :address1, :address2, :phone, :email)
  end
end

app/helpers/caseworkers_helper.rb
module CaseworkersHelper
end

app/views/caseworkers/_form.html.erb
<%= form_for(@caseworker) do |f| %>
  <% if @caseworker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caseworker.errors.count, "error") %> prohibited this caseworker from being saved:</h2>

      <ul>
      <% @caseworker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td><%= f.label :name %></td>
      <td><%= f.text_field :name %></td>
    </tr><tr>
    
      <td><%= f.label :organization %></td>
      <td><%= f.text_field :organization %></td>
    </tr><tr>
      <td><%= f.label :address1 %></td>
      <td><%= f.text_field :address1 %></td>
    </tr><tr>
      <td><%= f.label :address2 %></td>
      <td><%= f.text_field :address2 %></td>
    </tr><tr>
      <td><%= f.label :phone %></td>
      <td><%= f.text_field :phone %></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email %></td>
    </tr>
<% if current_user.is_admin? -%>
    <tr>
      <td><%= f.label :limit %></td>
      <td><%= f.text_field :limit %></td>
    </tr>
<% end -%>
  </table>
<br />
  <div class="actions"><%= f.submit "Update Info" %></div>
<% end %>

app/views/caseworkers/edit.html.erb
<h1>Edit Your Details</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Show', @caseworker %> |
<% if user_signed_in? -%>
<%= link_to 'Back', root_path %>
<% else -%>
<%= link_to 'Back', caseworkers_path %>
<% end -%>

app/views/caseworkers/index.html.erb
<h1>Listing caseworkers</h1>

<% if user_signed_in? && current_user.is_admin? -%>
You have <%= Client.count_new(current_user.last_sign_in_at) %> new client applications.  <%#link_to "See client applications", :controller => :clients, :view => :recent %> <%=link_to "See client applications", recent_clients_path %>
<% end -%>

<div id="data">
<table>
  <tr>
    <th>Name</th>
    <th>Organization</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Login</th>
  </tr>

<% @caseworkers.each do |caseworker| %>
  <tr>
    <td><%=h caseworker.name %></td>
    <td><%=h caseworker.organization %></td>
    <td><%=h caseworker.phone %></td>
    <td><%=h caseworker.email %></td>
    <td><%=h caseworker.user.email if caseworker.user %></td>
    <td><%= link_to 'Show', caseworker %></td>
    <td><%= link_to 'Edit', edit_caseworker_path(caseworker) %></td>
    <td><%= link_to 'Destroy', caseworker, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<% if user_signed_in? && current_user.is_admin? && false -%>
<%= link_to 'New caseworker', new_caseworker_path %>
<% end -%>

app/views/caseworkers/new.html.erb
<h1>New caseworker</h1>

<div id="data">
<%= render 'form' %>
</div>

<%= link_to 'Back', caseworkers_path %>

app/views/caseworkers/show.html.erb
<h1>Your information</h1>

<div id="data">
<p>
  <b>Name:</b>
  <%=h @caseworker.name %>
</p>

<p>
  <b>Organization:</b>
  <%=h @caseworker.organization %>
</p>

<p>
  <b>Address1:</b>
  <%=h @caseworker.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%=h @caseworker.address2 %>
</p>

<p>
  <b>Phone:</b>
  <%=h @caseworker.phone %>
</p>

<p>
  <b>Email:</b>
  <%=h @caseworker.email %>
</p>

<% if current_user.is_admin? -%>
<p>
  <b>Limit:</b>
  <%=h @caseworker.limit %>
</p>
<% end -%>
</div>

<% if can? :add, Client -%>
<p>
<%= link_to "Add Client Application", new_client_path %>
</p>
<% end %>

<%= link_to 'Edit', edit_caseworker_path(@caseworker) %> |
<% if user_signed_in? -%>
<%= link_to 'Back', root_path %>
<% else -%>
<%= link_to 'Back', caseworkers_path %>
<% end -%>

app/views/caseworkers/sign_in.html.erb
<h1>The Recyclery - Caseworker's Portal</h1>


<% if user_signed_in? && current_user.is_admin? -%>
<!-- Admin sees this -->
You have <%= Client.count_new(current_user.last_sign_in_at) %> new client applications.  <%#link_to "See client applications", :controller => :clients, :view => :recent %> <%=link_to "See client applications", recent_clients_path %>
<div><%= link_to "Show caseworkers", caseworkers_path %></div>
<% if false -%><div><%= link_to "Add a new caseworker", new_client_path %></div><% end -%>
<% elsif user_signed_in? && current_user.caseworker.name -%>
<!-- Caseworker sees this -->
<br />
<div><%= link_to "Show client applications", clients_path %></div>
<%   if current_user.caseworker.can_add_clients? -%>
<div><%= link_to "Add a new client", new_client_path %></div>
<%   end -%>
<br />
<div><%= link_to "Edit your details", edit_caseworker_path(current_user.caseworker) %></div>
<% elsif user_signed_in? -%>
<!-- Caseworker sees this first time -->
<div><%= link_to "Add your details", edit_caseworker_path(current_user.caseworker) %></div>
<% end -%>